version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x

  pre_build:
    commands:
      - yarn install --frozen-lockfile

  build:
    commands:
      - yarn build

  post_build:
    commands:
      - aws s3 sync --delete ./dist s3://${S3_BUCKET}
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/index.html"
